# Generated by Django 2.2.13 on 2020-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='categ',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='content_data',
            field=models.TextField(default={'document_pdf': False, 'quiz': False, 'serious_game': False, 'text_image': False, 'video': False, 'webzine': False}),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='editor',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='is_graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='is_required_atp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='categ',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='content_data',
            field=models.TextField(default={'document_pdf': False, 'quiz': False, 'serious_game': False, 'text_image': False, 'video': False, 'webzine': False}),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='editor',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='is_graded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='is_required_atp',
            field=models.BooleanField(default=False),
        ),
    ]
