# Generated by Django 2.2.13 on 2020-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0002_delete_trackinglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtcreated', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('username', models.CharField(blank=True, max_length=32)),
                ('ip', models.CharField(blank=True, max_length=32)),
                ('event_source', models.CharField(max_length=32)),
                ('event_type', models.CharField(blank=True, max_length=512)),
                ('event', models.TextField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=256)),
                ('page', models.CharField(blank=True, max_length=512, null=True)),
                ('time', models.DateTimeField(verbose_name='event time')),
                ('host', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'track_trackinglog',
            },
        ),
    ]
