# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-28 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tmaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, max_length=50)),
                ('course_id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255)),
                ('task_key', models.CharField(db_index=True, max_length=255)),
                ('task_input', models.TextField(default=False)),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('task_state', models.CharField(db_index=True, max_length=50, null=True)),
                ('task_output', models.CharField(max_length=1024, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subtasks', models.TextField(blank=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
