# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-28 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0007_auto_20200228_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversionconfig',
            name='platform',
            field=models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=50),
        ),
    ]
