# Generated by Django 2.2.13 on 2020-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0010_auto_20200605_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversionconfig',
            name='platform',
            field=models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS')], max_length=50),
        ),
    ]
