# Generated by Django 2.2.17 on 2022-07-19 04:47

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0039_userprofile_custom_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='WulCourseOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id_edx', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                ('course_timer_active', models.BooleanField(default=False)),
                ('course_timer_type', models.CharField(default='no_timer', max_length=255)),
                ('course_timer_days_value', models.IntegerField(blank=True, null=True)),
                ('course_timer_date_value', models.DateField(blank=True, null=True)),
                ('course_certificat_mode', models.CharField(default='default_mode', max_length=255)),
                ('course_certificat_detail', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WulCourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_time_tracking', models.IntegerField(default=0)),
                ('detailed_time_tracking', models.TextField(blank=True, default='{}')),
                ('daily_time_tracking', models.TextField(blank=True, default='{}')),
                ('has_started_course', models.BooleanField(default=False)),
                ('has_finished_course', models.BooleanField(default=False)),
                ('finished_course_date', models.DateTimeField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('best_grade', models.FloatField(db_index=True, default=0)),
                ('best_grade_date', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.TextField(blank=True, default='{}')),
                ('course_enrollment_edx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.CourseEnrollment', unique=True)),
            ],
        ),
    ]
