# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_creditrequirement_copy_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequirement',
            name='order',
        ),
    ]
