# Generated by Django 2.2.13 on 2020-06-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_userprofile_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, db_index=True, max_length=255)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('language', models.CharField(blank=True, db_index=True, max_length=255)),
                ('uuid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('level_1', models.CharField(blank=True, db_index=True, max_length=255)),
                ('level_2', models.CharField(blank=True, db_index=True, max_length=255)),
                ('level_3', models.CharField(blank=True, db_index=True, max_length=255)),
                ('level_4', models.CharField(blank=True, db_index=True, max_length=255)),
                ('last_invite', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user_preprofile',
            },
        ),
    ]
