# Generated by Django 2.2.17 on 2021-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_auto_20201021_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_field',
            field=models.TextField(default='{}'),
        ),
    ]
